######################################
## 4gekkman/docker-nginx_phpfpm-dev ##
######################################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Подавить сообщения error/warning от upstart
##  3. Дать контейнеру знать об отсутствии tty
##  4. Затереть скрипт /usr/sbin/policy-rc.d
##  5. Обновить все присутствующие пакеты
##  6. Установить необходимые пакеты
##  7. Создать следующие каталоги, если они отсутствуют
##  8. Удалить конфиги nginx и php
##  9. Сделать expose портов 80 и 443
##  10. Назначить cmd по умолчанию, запускающую supervisord
##  11. Установить composer
##  12. Скопировать /etc/cron.d задачи для cron
##

# 1. Базовый образ и разработчики
FROM ubuntu:16.04
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Подавить сообщения error/warning от upstart
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# 3. Дать контейнеру знать об отсутствии tty
ENV DEBIAN_FRONTEND noninteractive

# 4. Затереть скрипт /usr/sbin/policy-rc.d
# - Это позволит избежать появления ошибки: invoke-rc.d: policy-rc.d denied execution of start
# - Подробнее см.здесь: https://habrahabr.ru/post/247903/
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

# 5. Обновить все присутствующие пакеты
RUN apt-get update && apt-get -y upgrade

# 6. Установить необходимые пакеты
RUN apt-get update && apt-get install -y \

    curl \
    cron \
    supervisor \
    nginx \
    php7.0 php7.0-fpm php7.0-gmp php7.0-mbstring \
    git \
    php7.0-mysql \
    php7.0-curl \
    php7.0-gd \
    php7.0-intl \
    php7.0-mcrypt \
    php7.0-sqlite \
    php7.0-tidy \
    php7.0-xmlrpc \
    php7.0-xsl \
    php7.0-pgsql \
    php7.0-ldap \
    pwgen

# 7. Создать следующие каталоги, если они отсутствуют
RUN mkdir -p /etc/nginx
RUN mkdir -p /var/log/supervisor
RUN mkdir -p /var/run/php-fpm

# 8. Удалить конфиги nginx и php
# - А добавляться конфиги будет в compose-проекте
RUN rm /etc/nginx/nginx.conf
RUN rm /etc/php/7.0/fpm/php.ini

# 9. Сделать expose портов 80 и 443
EXPOSE 80
EXPOSE 443

# 10. Назначить cmd по умолчанию, запускающую supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor.d/supervisor.ini"]

# 11. Установить composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# 12. Скопировать /etc/cron.d задачи для cron
COPY ./cron/laravel /etc/cron.d/laravel
